package com.github.catvod.utils

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * [UriUtil] 的差分校验。
 *
 * ─── 为什么是"差分"而不是"照着 RFC 写期望值" ──────────────────────────
 * `UriUtil.resolve` 是 `android.net.Uri.resolve` 语义的一份**纯 JVM 复刻**，
 * 而 Android 那份在若干边界上**不等于** RFC 3986 §5.4 的表格（`.` / `..` 的处理尤其）。
 * 本项目要的是"与参考宿主行为一致"，不是"与 RFC 一致" —— 按 RFC 写期望值，
 * 测的是我的理解，不是这份移植对不对。
 *
 * 所以下表的**期望值全部由参考实现本身产出**：
 * 把 `TV-fongmi/catvod/.../UriUtil.java` 去掉两个 Android 依赖
 * （`TextUtils.isEmpty` → `s == null || s.isEmpty()`、`@Nullable` → 删）后
 * 在 JVM 上跑同一批输入，把输出原样抄进来。
 * 生成脚本与原始输出见 `.workbuddy/scripts/_uriref_java.txt`。
 *
 * ⚠️ `UriUtil` 在项目里的实际用途只有一个：JS 爬虫的**模块名归一化**
 * （`JsSpider` 的 `moduleNormalizeName`）。它错了的表现是
 * "drpy 源的相对 import 全部加载失败"，而报错在 QuickJS 内部、指不到这里。
 */
class UriUtilTest {

    @Test
    fun `与参考实现逐例一致`() {
        var checked = 0
        for ((base, ref, expected) in CASES) {
            assertEquals("resolve($base, $ref)", expected, UriUtil.resolve(base, ref))
            checked++
        }
        assertEquals(CASES.size, checked)
    }

    private companion object {
        /** (base, reference, 参考实现的输出)。由脚本从 Java 参考实现产出，不要手改。 */
        val CASES: List<Triple<String, String, String>> = listOf(
            Triple("http://a/b/c/d;p?q", "g:h", "g:h"),
            Triple("http://a/b/c/d;p?q", "g", "http://a/b/c/g"),
            Triple("http://a/b/c/d;p?q", "./g", "http://a/b/c/g"),
            Triple("http://a/b/c/d;p?q", "g/", "http://a/b/c/g/"),
            Triple("http://a/b/c/d;p?q", "/g", "http://a/g"),
            Triple("http://a/b/c/d;p?q", "?y", "http://a/b/c/d;p?y"),
            Triple("http://a/b/c/d;p?q", "g?y", "http://a/b/c/g?y"),
            Triple("http://a/b/c/d;p?q", "#s", "http://a/b/c/d;p?q#s"),
            Triple("http://a/b/c/d;p?q", "g#s", "http://a/b/c/g#s"),
            Triple("http://a/b/c/d;p?q", "g?y#s", "http://a/b/c/g?y#s"),
            Triple("http://a/b/c/d;p?q", ";x", "http://a/b/c/;x"),
            Triple("http://a/b/c/d;p?q", "g;x", "http://a/b/c/g;x"),
            Triple("http://a/b/c/d;p?q", ".", "http://a/b/c/"),
            Triple("http://a/b/c/d;p?q", "./", "http://a/b/c/"),
            Triple("http://a/b/c/d;p?q", "..", "http://a/b/"),
            Triple("http://a/b/c/d;p?q", "../", "http://a/b/"),
            Triple("http://a/b/c/d;p?q", "../g", "http://a/b/g"),
            Triple("http://a/b/c/d;p?q", "../..", "http://a/"),
            Triple("http://a/b/c/d;p?q", "../../", "http://a/"),
            Triple("http://a/b/c/d;p?q", "../../g", "http://a/g"),
            Triple("http://a/b/c/d;p?q", "./lib/x.js", "http://a/b/c/lib/x.js"),
            Triple("http://a/b/c/d;p?q", "../lib/x.js", "http://a/b/lib/x.js"),
            Triple("http://a/b/c/d;p?q", "lib/gbk.js", "http://a/b/c/lib/gbk.js"),
            Triple("http://a/b/c/d;p?q", "a.js", "http://a/b/c/a.js"),
            Triple("http://a/b/c/d;p?q", "/abs.js", "http://a/abs.js"),
            Triple("http://a/b/c/d;p?q", "//g", "http://g"),
            Triple("http://a/b/c/d;p?q", "?", "http://a/b/c/d;p?"),
            Triple("http://a/b/c/d;p?q", "#", "http://a/b/c/d;p?q#"),
            Triple("http://a/b/c/d;p?q", "", "http://a/b/c/d;p?q"),
            Triple("http://a/b/c/d;p?q", "sub/dir/mod.js", "http://a/b/c/sub/dir/mod.js"),
            Triple("http://host", "g:h", "g:h"),
            Triple("http://host", "g", "http://host/g"),
            Triple("http://host", "./g", "http://host/g"),
            Triple("http://host", "g/", "http://host/g/"),
            Triple("http://host", "/g", "http://host/g"),
            Triple("http://host", "?y", "http://host?y"),
            Triple("http://host", "g?y", "http://host/g?y"),
            Triple("http://host", "#s", "http://host#s"),
            Triple("http://host", "g#s", "http://host/g#s"),
            Triple("http://host", "g?y#s", "http://host/g?y#s"),
            Triple("http://host", ";x", "http://host/;x"),
            Triple("http://host", "g;x", "http://host/g;x"),
            Triple("http://host", ".", "http://host/"),
            Triple("http://host", "./", "http://host/"),
            Triple("http://host", "..", "http://host/"),
            Triple("http://host", "../", "http://host/"),
            Triple("http://host", "../g", "http://host/g"),
            Triple("http://host", "../..", "http://host/"),
            Triple("http://host", "../../", "http://host/"),
            Triple("http://host", "../../g", "http://host/g"),
            Triple("http://host", "./lib/x.js", "http://host/lib/x.js"),
            Triple("http://host", "../lib/x.js", "http://host/lib/x.js"),
            Triple("http://host", "lib/gbk.js", "http://host/lib/gbk.js"),
            Triple("http://host", "a.js", "http://host/a.js"),
            Triple("http://host", "/abs.js", "http://host/abs.js"),
            Triple("http://host", "//g", "http://g"),
            Triple("http://host", "?", "http://host?"),
            Triple("http://host", "#", "http://host#"),
            Triple("http://host", "", "http://host"),
            Triple("http://host", "sub/dir/mod.js", "http://host/sub/dir/mod.js"),
            Triple("http://host/", "g:h", "g:h"),
            Triple("http://host/", "g", "http://host/g"),
            Triple("http://host/", "./g", "http://host/g"),
            Triple("http://host/", "g/", "http://host/g/"),
            Triple("http://host/", "/g", "http://host/g"),
            Triple("http://host/", "?y", "http://host/?y"),
            Triple("http://host/", "g?y", "http://host/g?y"),
            Triple("http://host/", "#s", "http://host/#s"),
            Triple("http://host/", "g#s", "http://host/g#s"),
            Triple("http://host/", "g?y#s", "http://host/g?y#s"),
            Triple("http://host/", ";x", "http://host/;x"),
            Triple("http://host/", "g;x", "http://host/g;x"),
            Triple("http://host/", ".", "http://host/"),
            Triple("http://host/", "./", "http://host/"),
            Triple("http://host/", "..", "http://host/"),
            Triple("http://host/", "../", "http://host/"),
            Triple("http://host/", "../g", "http://host/g"),
            Triple("http://host/", "../..", "http://host/"),
            Triple("http://host/", "../../", "http://host/"),
            Triple("http://host/", "../../g", "http://host/g"),
            Triple("http://host/", "./lib/x.js", "http://host/lib/x.js"),
            Triple("http://host/", "../lib/x.js", "http://host/lib/x.js"),
            Triple("http://host/", "lib/gbk.js", "http://host/lib/gbk.js"),
            Triple("http://host/", "a.js", "http://host/a.js"),
            Triple("http://host/", "/abs.js", "http://host/abs.js"),
            Triple("http://host/", "//g", "http://g"),
            Triple("http://host/", "?", "http://host/?"),
            Triple("http://host/", "#", "http://host/#"),
            Triple("http://host/", "", "http://host/"),
            Triple("http://host/", "sub/dir/mod.js", "http://host/sub/dir/mod.js"),
            Triple("http://host/a/b.js", "g:h", "g:h"),
            Triple("http://host/a/b.js", "g", "http://host/a/g"),
            Triple("http://host/a/b.js", "./g", "http://host/a/g"),
            Triple("http://host/a/b.js", "g/", "http://host/a/g/"),
            Triple("http://host/a/b.js", "/g", "http://host/g"),
            Triple("http://host/a/b.js", "?y", "http://host/a/b.js?y"),
            Triple("http://host/a/b.js", "g?y", "http://host/a/g?y"),
            Triple("http://host/a/b.js", "#s", "http://host/a/b.js#s"),
            Triple("http://host/a/b.js", "g#s", "http://host/a/g#s"),
            Triple("http://host/a/b.js", "g?y#s", "http://host/a/g?y#s"),
            Triple("http://host/a/b.js", ";x", "http://host/a/;x"),
            Triple("http://host/a/b.js", "g;x", "http://host/a/g;x"),
            Triple("http://host/a/b.js", ".", "http://host/a/"),
            Triple("http://host/a/b.js", "./", "http://host/a/"),
            Triple("http://host/a/b.js", "..", "http://host/"),
            Triple("http://host/a/b.js", "../", "http://host/"),
            Triple("http://host/a/b.js", "../g", "http://host/g"),
            Triple("http://host/a/b.js", "../..", "http://host/"),
            Triple("http://host/a/b.js", "../../", "http://host/"),
            Triple("http://host/a/b.js", "../../g", "http://host/g"),
            Triple("http://host/a/b.js", "./lib/x.js", "http://host/a/lib/x.js"),
            Triple("http://host/a/b.js", "../lib/x.js", "http://host/lib/x.js"),
            Triple("http://host/a/b.js", "lib/gbk.js", "http://host/a/lib/gbk.js"),
            Triple("http://host/a/b.js", "a.js", "http://host/a/a.js"),
            Triple("http://host/a/b.js", "/abs.js", "http://host/abs.js"),
            Triple("http://host/a/b.js", "//g", "http://g"),
            Triple("http://host/a/b.js", "?", "http://host/a/b.js?"),
            Triple("http://host/a/b.js", "#", "http://host/a/b.js#"),
            Triple("http://host/a/b.js", "", "http://host/a/b.js"),
            Triple("http://host/a/b.js", "sub/dir/mod.js", "http://host/a/sub/dir/mod.js"),
            Triple("", "g:h", "g:h"),
            Triple("", "g", "g"),
            Triple("", "./g", "g"),
            Triple("", "g/", "g/"),
            Triple("", "/g", "/g"),
            Triple("", "?y", "?y"),
            Triple("", "g?y", "g?y"),
            Triple("", "#s", "#s"),
            Triple("", "g#s", "g#s"),
            Triple("", "g?y#s", "g?y#s"),
            Triple("", ";x", ";x"),
            Triple("", "g;x", "g;x"),
            Triple("", ".", ""),
            Triple("", "./", ""),
            Triple("", "..", ""),
            Triple("", "../", ""),
            Triple("", "../g", "g"),
            Triple("", "../..", ""),
            Triple("", "../../", ""),
            Triple("", "../../g", "g"),
            Triple("", "./lib/x.js", "lib/x.js"),
            Triple("", "../lib/x.js", "lib/x.js"),
            Triple("", "lib/gbk.js", "lib/gbk.js"),
            Triple("", "a.js", "a.js"),
            Triple("", "/abs.js", "/abs.js"),
            Triple("", "//g", "//g"),
            Triple("", "?", "?"),
            Triple("", "#", "#"),
            Triple("", "", ""),
            Triple("", "sub/dir/mod.js", "sub/dir/mod.js"),
            Triple("/a/b", "g:h", "g:h"),
            Triple("/a/b", "g", "/a/g"),
            Triple("/a/b", "./g", "/a/g"),
            Triple("/a/b", "g/", "/a/g/"),
            Triple("/a/b", "/g", "/g"),
            Triple("/a/b", "?y", "/a/b?y"),
            Triple("/a/b", "g?y", "/a/g?y"),
            Triple("/a/b", "#s", "/a/b#s"),
            Triple("/a/b", "g#s", "/a/g#s"),
            Triple("/a/b", "g?y#s", "/a/g?y#s"),
            Triple("/a/b", ";x", "/a/;x"),
            Triple("/a/b", "g;x", "/a/g;x"),
            Triple("/a/b", ".", "/a/"),
            Triple("/a/b", "./", "/a/"),
            Triple("/a/b", "..", "/"),
            Triple("/a/b", "../", "/"),
            Triple("/a/b", "../g", "/g"),
            Triple("/a/b", "../..", "/"),
            Triple("/a/b", "../../", "/"),
            Triple("/a/b", "../../g", "/g"),
            Triple("/a/b", "./lib/x.js", "/a/lib/x.js"),
            Triple("/a/b", "../lib/x.js", "/lib/x.js"),
            Triple("/a/b", "lib/gbk.js", "/a/lib/gbk.js"),
            Triple("/a/b", "a.js", "/a/a.js"),
            Triple("/a/b", "/abs.js", "/abs.js"),
            Triple("/a/b", "//g", "//g"),
            Triple("/a/b", "?", "/a/b?"),
            Triple("/a/b", "#", "/a/b#"),
            Triple("/a/b", "", "/a/b"),
            Triple("/a/b", "sub/dir/mod.js", "/a/sub/dir/mod.js"),
            Triple("https://x/y/z.js?q=1#f", "g:h", "g:h"),
            Triple("https://x/y/z.js?q=1#f", "g", "https://x/y/g"),
            Triple("https://x/y/z.js?q=1#f", "./g", "https://x/y/g"),
            Triple("https://x/y/z.js?q=1#f", "g/", "https://x/y/g/"),
            Triple("https://x/y/z.js?q=1#f", "/g", "https://x/g"),
            Triple("https://x/y/z.js?q=1#f", "?y", "https://x/y/z.js?y"),
            Triple("https://x/y/z.js?q=1#f", "g?y", "https://x/y/g?y"),
            Triple("https://x/y/z.js?q=1#f", "#s", "https://x/y/z.js?q=1#s"),
            Triple("https://x/y/z.js?q=1#f", "g#s", "https://x/y/g#s"),
            Triple("https://x/y/z.js?q=1#f", "g?y#s", "https://x/y/g?y#s"),
            Triple("https://x/y/z.js?q=1#f", ";x", "https://x/y/;x"),
            Triple("https://x/y/z.js?q=1#f", "g;x", "https://x/y/g;x"),
            Triple("https://x/y/z.js?q=1#f", ".", "https://x/y/"),
            Triple("https://x/y/z.js?q=1#f", "./", "https://x/y/"),
            Triple("https://x/y/z.js?q=1#f", "..", "https://x/"),
            Triple("https://x/y/z.js?q=1#f", "../", "https://x/"),
            Triple("https://x/y/z.js?q=1#f", "../g", "https://x/g"),
            Triple("https://x/y/z.js?q=1#f", "../..", "https://x/"),
            Triple("https://x/y/z.js?q=1#f", "../../", "https://x/"),
            Triple("https://x/y/z.js?q=1#f", "../../g", "https://x/g"),
            Triple("https://x/y/z.js?q=1#f", "./lib/x.js", "https://x/y/lib/x.js"),
            Triple("https://x/y/z.js?q=1#f", "../lib/x.js", "https://x/lib/x.js"),
            Triple("https://x/y/z.js?q=1#f", "lib/gbk.js", "https://x/y/lib/gbk.js"),
            Triple("https://x/y/z.js?q=1#f", "a.js", "https://x/y/a.js"),
            Triple("https://x/y/z.js?q=1#f", "/abs.js", "https://x/abs.js"),
            Triple("https://x/y/z.js?q=1#f", "//g", "https://g"),
            Triple("https://x/y/z.js?q=1#f", "?", "https://x/y/z.js?"),
            Triple("https://x/y/z.js?q=1#f", "#", "https://x/y/z.js?q=1#"),
            Triple("https://x/y/z.js?q=1#f", "", "https://x/y/z.js?q=1"),
            Triple("https://x/y/z.js?q=1#f", "sub/dir/mod.js", "https://x/y/sub/dir/mod.js"),
        )
    }
}
